### PR TITLE
fix: add more requirements to enable `lspsaga.symbol.head`

### PR DESCRIPTION
**Pull request by UrNightmaree**
related to #1199

### CODE REVIEW

**Comment by glepnir** [comment]
if build with a old commit I think there should notify a update message for use new event.

**Comment by UrNightmaree** [comment]
Maybe It's better to make config property that enable `lspsaga.symbol.head`, example: `lspsaga.setup{ enable_improved_symbol = true }`.

**Comment by glepnir** [comment]
nope if you are using nightly I think you need follow up commit not pin a commit .

**Comment by glepnir** [comment]
stylua lint fix.

**Pull request merged**
