### PR TITLE
version 0.3

### LINKED ISSUE #805: Show "implementations" and "parent/interface" signs in the signcolumn
**Is your feature request related to a problem? Please describe.**
I configured my LSP, and it works fine. I'm looking for a way to show these kinds of icons in my `signcolumn` for Golang. If it could work for other programming languages, that would be great.

image

It helps me to get it quickly that this is an interface implementation or this interface has implementation somewhere.

**Describe the solution you'd like**
Showing `implementations` and `parent/interface` icons in the sign column. 

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #985: Open finder in a horizontal split
**Is your feature request related to a problem? Please describe.**

When performing elaborate analysis of references, the floating window UI of the finder is not always convenient. In this scenario you need to jump to the code, navigate around, then move back to the finder results and continue with the next reference. If you lose the floating window in the meantime, it's frustrating as you need to start over.

**Describe the solution you'd like**

- Have a config option to render the finder in the horizontal split.
- The horizontal split should have two columns - one for finder results, and one for preview (e.g. `:sp` for finder results and `:vs` for preview).
- The split should take the full width (in case you have vertical splits), e.g. `<C-w>J` or `<C-w>K`. This could also be configurable, by default it should be bottom.
- Add a config option to leave the finder open after opening the code link. In this case, the finder should be closed manually by the user.
- If the finder stays open after opening the link, the next reference search should reuse the open split.

**Describe alternatives you've considered**

An alternative could be sending the finder results to the quickfix list. But that is not as convenient, since now you have a different UI and without previews. The sending to the quickfix could be implemented as a separate feature though.

**Additional context**

Here is a quick prototype:

https://user-images.githubusercontent.com/16953692/229222320-39afea47-642c-4b72-82da-8bc0c84f895a.mov

### LINKED ISSUE #988: Custom filtering of references and incoming/outgoing calls
**Is your feature request related to a problem? Please describe.**

When analyzing references or incoming/outgoing calls, not all results are equally valuable to the user. The two common examples are:

1. References in tests. It often happens that your function is referenced 5 times in production code, and 47 times in tests. When you are analyzing the production code, seeing all the test references just stands in the way.
2. References in generated code. Some projects have generated code in their sources. The close analogy is tree-sitter parser - it's C code which is fully generated from the grammar. When you search for references, the usages in the generated code are not usually of interest.

**Describe the solution you'd like**

It would be cool to let the users define custom filter functions for references and incoming/outgoing calls. 

There are 2 possible implementation options:

**Option A: Custom predefined filters.**

1. In the config, the user defines custom filter functions:
```lua
require("lspsaga").setup({
  finder = {
    filters = {
      {
        name = "Tests",
        fn = function(entry)
          return entry.file_name ends with "_test.ts"
        end
      },
      {
        name = "Generated code",
        fn = function(entry)
          return entry.file_name ends with "_generated.ts"
        end
      }
    }
  }
})
```

The entry to the filter `fn` could be whatever object is returned by the LSP server. 

2. In the finder window, add a function to apply a filter to the results. There should be two types of filters: `include` and `exclude`. 
For example:
- The user presses `<Leader>fe` (filter exclude)
- The plugin presents the list of available filters in the menu ("Tests", "Generated code"), e.g. like code actions.
- The user chooses "Tests" from the menu.
- The finder results are re-rendered accordingly, taking the filters into account - all references in tests will now be hidden
- The user could apply more filters like this, including and excluding various results. 

Option A pros: quick filtering on commonly used expressions.
Option A cons: not possible to filter dynamically. Let's say at some point you need to filter on all files under `/src/backend`. You'd need first to define such a filter, and restart neovim.

**Option B: Dynamic file path filters**

Instead of defining the static filter functions in the config, the UI can support dynamic filtering on the file paths based on some regex.

For example:
- The user presses `<Leader>fe` (filter exclude)
- The plugin shows the text input for the filter expression. 
- The user types `_test.ts|_generated.ts`. This means exclude all files which end with _test.ts or _generated.ts.
- The finder results are re-rendered accordingly, taking the filters into account.
- The user can edit the filters as needed.

Option B pros: dynamic filtering on anything.
Option B cons: for commonly filters (e.g. _test.ts) need to re-type the same filter each time. This could be mitigated by preserving the filters when the UI is closed, or by adding shortcuts to define custom filter strings.

**Applicable to both options**

* The filters should be saved when closing and reopening the UI (possibly with a config option to disable).
* The current filter selection can be shown in the winline of the finder, for example:
   
   ```
   Filters: include "Tests", exclude "Generated code"
   ```

**Describe alternatives you've considered**

Not sure there is anything.

### LINKED ISSUE #1000: disable folder/indentation in lsp_finder
Again, thank you for this awesome project.

Recently the lsp_finder changed the Definition/Implements/References view to show a folder layout with indentation, is there any way to disable this?

How I would like it:
image

How it currently is:
image

### LINKED ISSUE #1005: Add unit test pipeline
It would be nice to add unit test pipeline to avoid potential trivial mistakes (typo's for instance). Each feature should be merged to `main` branch after CI verification. Thus, it will prevent anyone from breaking the plugin.

### LINKED ISSUE #1023: Allow users to have a stack of "peek_definition" floating windows
**Describe the solution you'd like**
When you call `peek_definition` from the peek definition window, a new float would open and so on. Essentially making a stack of floating windows.
Pressing `q` inside the latest float would take you back to the previous float, etc until you have exited all the floats.

This feature used to exist, but has been removed lately and now there's only ever one peek_definition float open at any given time.

I'm not sure why this was changed in the first place, but maybe providing a user configurable option would make sense; like adding this to the `peek_definition` options:

```diff
  definition = {
    edit = "<C-c>o",
    vsplit = "<C-c>v",
    split = "<C-c>i",
    tabe = "<C-c>t",
    quit = "q",
+   stacked = true
  }
```

### LINKED ISSUE #1030: code actions return deepcopy error when call in certain lines
### Describe the bug

When call code actions on Importing dependency, create class, sort members, convert to blocks body works as expected the code actions popup shows.
When expected code actions is about wrap with widget or remove widget etc. it will return this error without the code actions popup shows.
image

Error executing vim.schedule lua callback: vim/shared.lua:0: Cannot deepcopy object of type userdata
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:203: in function 'callback'
...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1951: in function 'handler'
...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue

### Steps to reproduce

call lspsaga code action in any Widget build()
see deepcopy error

### Expected behavior

I expected it the code actions to works for all cases.

### Neovim version (nvim -v)

v0.8.2

### lspsaga commit

c7cc005ba2600c3eaf2bddb2b631ecc9d63b2ba8

### Terminal name/version

macOS iterm2

### LINKED ISSUE #1044: [Feature Request] show source in any diagnostic show window.
### Describe the bug

Despite setting diagnostic.show_source = true, the diagnostic message shown by lspsaga still doesn't render the source of the message. The screenshot below compares the message with what's shown when setting source=true in virtual_text through vim.dianostic.config. 

image

### Steps to reproduce

```lua
require('lspsaga').setup({
  symbol_in_winbar = {
    enable = false,
  },
  lightbulb = {
    virtual_text = false,
  },
  diagnostic = {
    on_insert = false,
    show_source = true,
    keys = {
      quit_in_show = { 'q', '<ESC>' },
    },
  },
  code_action = {
    keys = {
      quit = { 'q', '<ESC>' },
      exec = '<CR>',
    },
  },
})
```

### Expected behavior

source of the diagnostic message is "typescript". It should get rendered in the lspsaga diagnostic window. 

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

32a9dca

### Terminal name/version

Windows Terminal

### LINKED ISSUE #1047: View Document
### Describe the bug

Opening link from view document on hover not working when press gx on top of view documents.

image

### Steps to reproduce

OS: Windows

Steps:
press f to use lspsaga hover, press f again to get inside hover, set cursor on top of view documents and press gx to open link

### Expected behavior

Open link of view documents in browser

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

none

### Terminal name/version

Powershell

### LINKED ISSUE #1049: Open peek definition break transparency
### Describe the bug

When you open a window with peek_definition the transparency is broken, is full black background.

Video:

https://user-images.githubusercontent.com/44141208/235259672-38a19344-2bc3-43b8-a1f2-26c87757d5ee.mp4

Config:

```lua
saga.setup({
  ui = {
    winblend = 10,
    border = 'rounded',
    colors = {
      normal_bg = "NONE",
    }
  },
  beacon = {
    enable = false,
  }
})
```

### Steps to reproduce

- Open a file
- Move cursor over a function
- Use hover_doc and validate transparency is ok
- Use Lspsaga peek_definition over the function and close
- Validate background color is not more transparent

### Expected behavior

When open peek_definition and close the window transparency don't change

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

32a9dca

### Terminal name/version

Kitty 0.26.5

### LINKED ISSUE #1057: Outline not working with rescript project
### Describe the bug

Nothing happens using the `Lspsaga outline` command in a Rescript project.

If the command is executed again the message `[lspsaga.nvim] there is already a request for outline please wait` shows in the status line. 

### Steps to reproduce

Using rescriptls as language server, run `Lspsaga outline` in a rescript file with any kind of data inside.

### Expected behavior

The outline to shows up

### Neovim version (nvim -v)

0.9.0 release

### lspsaga commit

76696bed4397c3b58563c246dc1f7856ed4af023

### Terminal name/version

Iterm 2 in macos Ventura

### LINKED ISSUE #1058: Code actions get stuck (due to new preview window)
### Describe the bug

I've just had to restart Neovim completely due to an unrecoverable issue with Lspsaga.

The good news is that it shouldn't be too difficult to fix!

I'm working in Dart on a Flutter project. I've noticed that Lspsaga has a nice new feature that kicks in with code actions — when you a ready to perform a code action, there's a little preview window that pops up showing what the effects of the action will be.

It's nice, but the few bugs in this new system need dealing with:

Issues:

1) When the main "code actions" window is closed *manually* (e.g. using `<C-w>q`) , this popup window persists.

Desired behaviour: It should be closed along with the code action window.

**Bonus feature request**: Let's have the ability to cancel code actions quickly and easily  by pressing `q`, similar to many other popup windows in the Neovim ecosystem. Maybe  by`<Esc>` as well.

(It's very important to be able to close the code action window quickly as often the code action you expect to see is not available. This is something I need several times per hour of work)

2) Once the secondary popup is stuck hovering solo over my screen, there's no way to close it—the window is unselectable.

Desired behaviour: I'm sure the fact that the window is unselectable is desired. Cause this window to sync with the main code actions window and this problem disappears. However, it's extremely disruptive and difficult to get rid of in its current state.

3) After aborting a code action this way, the code action interface is unusable Any attempts to use a code action with the same server return an error message: `[lspsaga.nvim] there is already a code action request please wait`

Desired behaviour: It should be extremely hard to reach this state using normal LSP usage. While fixing the popup window problem may solve this, I can't really think of a case where a code action request or return could legitimately get 'stuck' save for the UI being left open by the user.

**Bonus feature request**: Some kind of `Lspsaga reset` command that would close all windows and reset Lspsaga to its default state in case of such an emergency

### Steps to reproduce

See above — closing the code action window while leaving the its sibling 'preview' window open.

### Expected behavior

See above — Lspsaga shouldn't get in any kind of 'stuck' state.

### Neovim version (nvim -v)

0.9

### lspsaga commit

main: 76696be chore(doc): auto generate docs

### Terminal name/version

kitty

### LINKED ISSUE #1070: Finder triggers telescope buffers for some reason
### Describe the bug

I have default configuration for both [telescope](https://github.com/vitarb/nvim-config/blob/saga/lua/plugins/setup/telescope.lua) and [lspsaga](https://github.com/vitarb/nvim-config/blob/saga/lua/plugins/setup/lspsaga.lua). Full config available here: https://github.com/vitarb/nvim-config/tree/saga

### Steps to reproduce

When I use lsp_finder or other saga commands like incoming/outgoing calls, telescope "buffers" window gets opened in the background:

I have no shortcut conflicts, and tried remapping saga commands to different key combinations, but still seeing same issue.

### Expected behavior

No telescope window should be open on reference search.

### Neovim version (nvim -v)

v0.9.0

### lspsaga commit

latest

### Terminal name/version

alacritty

### LINKED ISSUE #1076: [0.3.0]  file path back to finder title
When searching for references of a method, I use `lsp_finder` however from the generated list I cannot see what file is on the preview panel on the right

This is how Telescope shows the preview panel
image

This is how lspsaga renders the panel
image

### LINKED ISSUE #1079: Hover bug when buffer have one more servers and both have hover request  resonse
### Describe the bug

as trace of #865

### Steps to reproduce

```lua
vim.opt.rtp:append('~/Workspace/lspsaga.nvim')
vim.opt.rtp:append('~/Workspace/nvim-lspconfig')
vim.opt.rtp:append('~/.local/share/nvim/lazy/nvim-treesitter/')
require('nvim-treesitter').setup({})

local lspconfig =require('lspconfig')
lspconfig.tsserver.setup({})
lspconfig.custom_elements_ls.setup({})

local keymap = vim.keymap.set
require("lspsaga").setup({})
keymap("n", "K", "<cmd>Lspsaga hover_doc<CR>")
```

### Expected behavior

works fine

### Neovim version (nvim -v)

head

### lspsaga commit

ref

### Terminal name/version

kitty

### LINKED ISSUE #1082: Invalid opt.height for action_preview
### Describe the bug

the function 
```lua
window.create_win_with_border(content_opts, opt)
```
is called with opt.height with value less then zero, so it get an error

### Steps to reproduce

- open neovim
- resize terminal window with very few lines
- run :Lspsaga code_actions<cr>

### Expected behavior

Do not show the action_preview

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

01b9633

### Terminal name/version

foot 1.14.0

### LINKED ISSUE #1085: Using existing windows to open definition/reference/etc.
**Is your feature request related to a problem? Please describe.**
It's not really a "problem", per se, but mostly, a nice-to-have feature.

**Describe the solution you'd like**
It happens to me a lot that I have something like this:
- I have 2 or 3 splits open
- In one of the splits, I open the peek definition window (or the finder window etc.)
- I want to open definition/reference etc, but:
  - I do not want to open it in the split I'm currently in
  - I want to open it in one of the other splits that I have open.

**Describe alternatives you've considered**
Right now, this is what I do:
- I go to the split I want to use for definition/reference
- I close it
- I go back to the split I want to see the definition for
- I then choose to open in horizontal/vertical split and `lspsaga` creates a new one

What I have in mind is something like `neo-tree`'s "open with window picker", but in the context of `lspsaga` and "open in split" for definitions/references

**Additional context**
Please let me know if what I descirbed makes sense, or if you need things such as screenshots

### LINKED ISSUE #1092: Provide API to check if rename popup is open
**Is your feature request related to a problem? Please describe.**
In order to avoid clashing with other plugins I'd like to be able to check wether the rename popup is open. For example, I want to disable `nvim-cmp` when I'm renaming a variable

**Describe the solution you'd like**
I haven't found a solution yet. Checking at the code,  I don't see a function that I could use

**Describe alternatives you've considered**
None

**Additional context**
None

### LINKED ISSUE #1094: Outgoing calls functionality is buggy
### Describe the bug

The current state of outgoing calls function makes it impossible to use.

Preview:

https://github.com/nvimdev/lspsaga.nvim/assets/5938539/e134772d-c75c-4003-a22c-97d59cd70b73

### Steps to reproduce

Open project with large history for outgoing calls

1. Enter command `Lspsaga outgoing_calls`
2. Press `u` on different entries multiple times (At this time highlighting should already be broken)
3. Press `o` to jump on floating file
4. Press `c-W, K` to jump outside floating window (At this time it's impossible to hide window)
5. If I enter `Lspsaga outgoing_calls` again and press Q it becomes even worse:

image

### Expected behavior

1. Enter command `Lspsaga outgoing_calls`
2. Press `u` on different entries multiple times (At this time highlighting still working)
3. Press `o` to jump on the floating file
4. Press `c-W, K` to jump outside the floating window (At this time it's possible to hide the window)

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### lspsaga commit

c475ace

### Terminal name/version

Aalcritty 0.12.1

### LINKED ISSUE #1096: Saga opens a buffer instead of a floating window
I've seen, that saga can live in a floating window if I go to a declaration and I very like to use it that way. I didn't have figured out by now why it doesn't work.

Can anybody help me?

This is my saga config:
```
-- Import LSP Saga plugin with a protected call:
local lspsaga_status_ok, lspsaga = pcall(require, 'lspsaga')
if not lspsaga_status_ok then
  return
end


------------------------------------------------------------
-- Appearance

lspsaga.setup({
  -- keybinds for navigation in lspsaga window
  scroll_preview = { scroll_down = "<C-f>", scroll_up = "<C-b>" },
  -- use enter to open file with definition preview
  definition = {
    edit = "<CR>",
  },
  ui = {
    title = true,
    border = "single",
  },
})

vim.api.nvim_set_hl(0, "TitleString", { fg = "#ababab", bg = "#252525" })
vim.api.nvim_set_hl(0, "TitleIcon", { fg = "#252525", bg = "#252525" })
vim.api.nvim_set_hl(0, "SagaBorder", { fg = "#252525", bg = "#252525" })
vim.api.nvim_set_hl(0, "SagaNormal", { bg = "#252525" })
vim.api.nvim_set_hl(0, "SagaExpand", { fg = "#252525", bg = "#252525" })
vim.api.nvim_set_hl(0, "SagaCollapse", { fg = "#252525", bg = "#252525" })
vim.api.nvim_set_hl(0, "SagaCount", { fg = "#252525", bg = "#252525" })
vim.api.nvim_set_hl(0, "SagaBeacon", { fg = "#252525", bg = "#252525" })

-- https://github.com/nvimdev/lspsaga.nvim/blob/main/lua/lspsaga/highlight.lua

------------------------------------------------------------
-- Key Mappings

local keymap = vim.keymap.set
keymap('n','gd', '<cmd>Lspsaga goto_definition<CR>')
```

### LINKED ISSUE #1099: Outline buffer cannot be pinned
### Describe the bug

I tried to use the [stickybuf](https://github.com/stevearc/stickybuf.nvim) plugin, so that opening new files in the outline buffer would not be possible. But this isn't working.

### Steps to reproduce

> :e ftplugin/lspsagaoutline.lua

`require('stickybuf').pin_filetype()`

### Expected behavior

Lspsaga outline buffer is pinned to the right and cannot open any other filetype

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

4f07545

### Terminal name/version

tmux 3.3a

### LINKED ISSUE #1102: [feat] add `max_width` to all different views
**Is your feature request related to a problem? Please describe.**
Yes, `finder` always occupies all the width available
sagafinder

**Describe the solution you'd like**
This could be solved in different ways
- Add `max_width` to the configuration of each view
- Add `max_width` to the global `preview` config
- Add `max_width` in `ui` conifg.

Each view should respect its local `max_width` or fallback to the global one

**Describe alternatives you've considered**
I don't see any workaround

**Additional context**
-

### LINKED ISSUE #1103: close_in_preview key not working in lsp_finder
### Describe the bug

With the default configuration, pressing `<esc>` does nothing when inside the preview window of the finder.

### Steps to reproduce

1. In any applicable file, invoke the `:Lspsaga lsp_finder` command.
2. Press `p` to jump to the preview window.
3. Press `esc`. Notice how the window isn't closed.

### Expected behavior

As the documentation says, I expect `esc` to close all windows from the finder.

Also, when looking at the source code I discovered that the mapping is [just removed](https://github.com/nvimdev/lspsaga.nvim/blob/4f075452c466df263e69ae142f6659dcf9324bf6/lua/lspsaga/finder.lua#L922), but I didn't find a place where it is actually set (like it is done for the [other mappings](https://github.com/nvimdev/lspsaga.nvim/blob/4f075452c466df263e69ae142f6659dcf9324bf6/lua/lspsaga/finder.lua#L620)).

### Neovim version (nvim -v)

NVIM v0.10.0-dev-523+gbbb934e77-Homebrew

### lspsaga commit

4f07545

### Terminal name/version

iterm2 3.4.19

### LINKED ISSUE #1104: `++keep` on everything
hover_doc allows `++keep` to be passed to keep hover window in the top right hand corner, this would be great if I could do this for every single command that issues a popup.

### LINKED ISSUE #1105: Save all buffers affected by `rename`
**Is your feature request related to a problem? Please describe.**
When I rename something across a project, I need to save all affected buffers manually.

**Describe the solution you'd like**
Provide an option to auto-save all affected buffers after renaming.

**Describe alternatives you've considered**
Providing an option to execute custom callback after the `rename` action.

### LINKED ISSUE #1107: Code Action doesn't work for C# with Omnisharp
### Describe the bug

Code actions through lspsaga works for other languages except C# using Omnisharp.
Either through number selection or by <CR>
since I have it set like this.
```
	code_action = {
		num_shortcut = true,
		keys = {
			quit = "<ESC>",
			exec = "<CR>",
		},
	},
````

Code actions through telescope work just fine for all languages including C#, so I thought it might be an issue with lspsaga itself.

### Steps to reproduce

Go do a location with code action available.
`:Lspsaga code_action`
Select code action (by number shortcut or <CR>)

### Expected behavior

Code action applies

### Neovim version (nvim -v)

NVIM v0.10.0-dev-590+ge85e7fc7b

### lspsaga commit

4f075452c466df263e69ae142f6659dcf9324bf6 HEAD -> main

### Terminal name/version

kitty 0.28.1

### PR DESCRIPTION
**Pull request by glepnir**
fully rewrite all . new usage take a look at https://dev.neovim.pro

Fix #805 Fix #985 Fix #988 Fix #1000 Fix #1005  Fix #1023  Fix #1030  Fix #1044 Fix #1047  Fix #1049  Fix #1057
Fix #1058 Fix #1070 Fix #1076  Fix #1079 Fix #1082  Fix #1085 Fix #1092 Fix #1094 Fix #1096 Fix #1105 Fix #1104 Fix #1103  Fix #1102 Fix #1099 Fix #1107

### CODE REVIEW

**Comment by glepnir** [comment]
Diagnostic
image

Untitled

image

image

image

image

**Comment by glepnir** [comment]
definition

image

**Comment by glepnir** [comment]
image
image

**Comment by glepnir** [comment]
image

image

**Comment by glepnir** [comment]
image

**Comment by glepnir** [comment]
image

**Comment by glepnir** [comment]
Untitled

**Comment by glepnir** [comment]
image

**Comment by glepnir** [comment]
image

Untitled

**Comment by glepnir** [comment]
logo

**Comment by mikehaertl** [comment]
@glepnir This looks nice! Will there also be a help file included? Or is it only available on the website?

**Comment by glepnir** [comment]
I am thinking use an github action sync doc .but now just website.

**Comment by digitallyserviced** [comment]
@glepnir 
i've just loaded version_3 branch... and i seem to be having an issue with finder since doing so. 

i first noticed that the argument to Lspsaga finder is now `finder` instead of `lsp_finder`? SO that tossed some errors on old mappings, no problem. When i changed the argument to just `finder` it doesn't throw an error, and instead has a polite error about no definition/reference. this is whether i shortcutkey it or call it from cmdline 

the quicklist you see in the following screen is there from nvchad, so my LSP is definitely still working.... 
image


here is my opts.... one thing i have noticed is that the docs have a `ft` property for the lazy config...  or a note about specifying lspsaga as an `lspconfig` dependency? 

To be honest I am not clear how to go about doing that when using nvchad as the base config. Can you suggest how to do that? Or can you maybe clarify the `ft` property correct options that would go there so that I can avoid having my dick folded in half by nvchad's core configs? 

I've always had the `LspAttach` event property since previous versions and seems to be only way to even get Lazy to load the thing. 

Sorry for not being too privy on the nvim plugin front, this lazy shit makes no sense to me sometimes, 300ms isnt a big deal, but i dunno how to turn it all off

```lua
/// lazy table entry
{
    "nvimdev/lspsaga.nvim",
    branch='version_3',
    event = "LspAttach",
    config = function()
          require "custom.configs.lspsaga"
  end,
  },

//req'd lua that calls setup with these opts


lspsaga.setup {
  preview = {
    lines_above = 0,
    lines_below = 10,
  },
  scroll_preview = {
    scroll_down = "<C-f>",
    scroll_up = "<C-b>",
  },
  -- definition = {
  --   edit = "<C-c>o",
  --   vsplit = "<C-c>v",
  --   split = "<C-c>i",
  --   tabe = "<C-c>t",
  --   quit = "q",
  --   close = "<Esc>",
  -- },
  code_action = {
    num_shortcut = true,
    keys = {
      -- string |table type
      quit = { "q", "<ESC>" },
      exec = "<CR>",
    },
  },
  request_timeout = 2000,
  callhierarchy = {
    show_detail=true,
max_height=0.55,
    layout = 'normal',
    left_width=0.25,
    keys = {
      edit = { "o", "<CR>" },
      vsplit = "s",
      split = "i",
      tabe = "t",
      quit = { "q", "<ESC>" },
    }
  },
  finder = {
max_height=0.55,
    layout = 'normal',
    left_width=0.25,
    -- default='ref+tyd+imp+def',
    -- methods = {
    --   tyd = 'textDocument/typeDefinition',
    -- },
    keys = {
      edit = { "o", "<CR>" },
      vsplit = "s",
      split = "i",
      tabe = "t",
      quit = { "q", "<ESC>" },
    }
  },
  lightbulb = {
    enable = false,
    enable_in_insert = true,
    sign = true,
    sign_priority = 40,
    virtual_text = true,
  },
  diagnostic = {
    show_code_action = true,
    show_source = true,
    jump_num_shortcut = true,
    keys = {
      exec_action = "o",
      quit = { "q", "<ESC>" },
      go_action = "g",
    },
    theme = {},
  },
  outline = {
    win_position = "right",
    win_with = "",
    win_width = 30,
    show_detail = true,
    auto_preview = true,
    auto_refresh = true,
    auto_close = true,
    custom_sort = nil,
    keys = {
      jump = "o",
      expand_collapse = "u",
      quit = "q",
    },
  },
  symbol_in_winbar = {
    enable = true,
    separator = " ",
    hide_keyword = true,
    show_file = true,
    folder_level = 2,
    respect_root = false,
    color_mode = true,
  },
  ui = {
    -- currently only round theme
    theme = "round",
    -- this option only work in neovim 0.9
    title = true,
    -- border type can be single,double,rounded,solid,shadow.
    border = "rounded",
    winblend = 0,
    expand = "",
    collapse = "",
    preview = " ",
    code_action = "💡",
    diagnostic = "🐞",
    incoming = " ",
    outgoing = " ",
    colors = {
      --float window normal background color
      normal_bg = "#000000",
      --title background color
      title_bg = "#FF7070",
      red = "#e95678",
      magenta = "#b33076",
      orange = "#FF8700",
      yellow = "#f7bb3b",
      green = "#afd700",
      cyan = "#36d0e0",
      blue = "#61afef",
      purple = "#CBA6F7",
      white = "#d1d4cf",
      black = "#1c1c19",
    },
    kind = { ["Folder"] = { "  ", "@comment" } },
  },
}


```

**Comment by glepnir** [comment]
if you are using lazy.nvim should update to latest. before lazy has a bug on `LspAttach` . about this warning could you try update ?

**Comment by digitallyserviced** [comment]
@glepnir I have updated and synced lazy/lspsaga/nvchad to latest and i see the new polite error message...

when doing other things like peek/hover it works fine and pulls full info... just finder not doing great... im going to try and nuke my confs down a bit to see if there's something with that in the way

**Comment by glepnir** [comment]
can you provide an example code that the `finder ` not work ? and which servers you used for this file ? I am gonna to reproduce .

**Comment by glepnir** [comment]
image

**Pull request merged**
