### PR TITLE
Add option to set initial mode for rename

### PR DESCRIPTION
**Pull request by nakatuba**
Thank you for providing such a great plugin.
I want to add an option to rename in insert mode because sometimes I want to change only a part of a variable or function name.

### CODE REVIEW

**Comment by glepnir** [comment]
so you can just  set `in_select` to false why change name ? it's break change

**Comment by nakatuba** [comment]
Currently the only options for initial mode are select mode and normal mode. I want to start in insert mode.

**Comment by glepnir** [comment]
why we not add an command option to do this  eg `:Lspaga rename mode=i/n/s` then it more useful . if you want change  all you can use `mode=s` if you want change part you can use `n or i`

**Comment by nakatuba** [comment]
Yes, that would be better, because you can use it in different modes.

**Comment by glepnir** [comment]
yup . this is more powerful then change in options . so I prefer we add a command argument for rename

**Comment by nakatuba** [comment]
This pull request is closed because adding command options may change the behavior of other APIs. I'll appreciate it if you could implement this in the future.

**Comment by glepnir** [comment]
will do in next version . create a feature request as trace.

**Comment by nakatuba** [comment]
I see. I appreciate your response and work.

**Pull request closed without merging**
