### PR TITLE
fix(outline): calc width/height for preview win based on columns

### PR DESCRIPTION
**Pull request by Alienover**
Before:

https://github.com/user-attachments/assets/e55c451d-3286-4bc1-b06f-28e7597561f0

After:

https://github.com/user-attachments/assets/23200acb-7200-4a90-a5b0-476469216a59

### CODE REVIEW

**Comment by 1538379200** [comment]
Are they the same issue? #1469

**Comment by Alienover** [comment]
> Are they the same issue? #1469

nope. this is only about the `outline` functionality.

**Comment by glepnir** [comment]
test failed ?

**Comment by Alienover** [comment]
@glepnir it looks like it failed to setup the Lua environment
image

**Comment by glepnir** [comment]
Oh i forget  update there the luajit shoud redirect.

**Comment by Alienover** [comment]
@glepnir Anything me or you can do to fix the test? or should we just continue this PR?

**Comment by glepnir** [comment]
thanks its not related.

**Pull request merged**
