### PR TITLE
feat: add padding+hl to code_action servers

### PR DESCRIPTION
**Pull request by KevinSilvester**
* Added padding before the showing server name for better readability
* Created a new highlight group for server names

---

**Before**
image

**After**
image

---

**Before**
image

**After**
image

### CODE REVIEW

**Comment by glepnir** [comment]
seems like top border is hidden ?

**Comment by KevinSilvester** [comment]
I think that may be due to a separate issue with the preview window.

I haven't really looked into the cause of the issue.
But from my experience the preview window sometimes appears underneath Code Actions window when:
   * There are a lot actions available for that line
   * The cursor is nearer the top of the buffer.

Plus all the screenshots under 'Before' were using the current main branch of `lspsaga` without any changes to its code.
The is another screen recording of the window overlap when using the main branch.

https://github.com/nvimdev/lspsaga.nvim/assets/56918431/cd591e4d-f504-4bec-8e3b-057bd6452420

**Comment by glepnir** [comment]
After new refactor so do we still this now ?

**Comment by KevinSilvester** [comment]
Yup all good to go.
The refactor seems to have fixed the overlapping issue

image

**Comment by glepnir** [comment]
oh next step is refactor the ui of code action :) diagnostic jump more fancy now :p

**Pull request closed without merging**
